// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: dns.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DNS RR type / QTYPE values (RFC 1035 + extensions)
type DnsType int32

const (
	DnsType_DNS_TYPE_UNSPECIFIED DnsType = 0
	DnsType_DNS_TYPE_A           DnsType = 1
	DnsType_DNS_TYPE_NS          DnsType = 2
	DnsType_DNS_TYPE_MD          DnsType = 3
	DnsType_DNS_TYPE_MF          DnsType = 4
	DnsType_DNS_TYPE_CNAME       DnsType = 5
	DnsType_DNS_TYPE_SOA         DnsType = 6
	DnsType_DNS_TYPE_MB          DnsType = 7
	DnsType_DNS_TYPE_MG          DnsType = 8
	DnsType_DNS_TYPE_MR          DnsType = 9
	DnsType_DNS_TYPE_NULL        DnsType = 10
	DnsType_DNS_TYPE_PTR         DnsType = 12
	DnsType_DNS_TYPE_HINFO       DnsType = 13
	DnsType_DNS_TYPE_MINFO       DnsType = 14
	DnsType_DNS_TYPE_MX          DnsType = 15
	DnsType_DNS_TYPE_TXT         DnsType = 16
	DnsType_DNS_TYPE_RP          DnsType = 17
	DnsType_DNS_TYPE_AFSDB       DnsType = 18
	DnsType_DNS_TYPE_X25         DnsType = 19
	DnsType_DNS_TYPE_ISDN        DnsType = 20
	DnsType_DNS_TYPE_RT          DnsType = 21
	DnsType_DNS_TYPE_NSAP_PTR    DnsType = 23
	DnsType_DNS_TYPE_SIG         DnsType = 24
	DnsType_DNS_TYPE_KEY         DnsType = 25
	DnsType_DNS_TYPE_PX          DnsType = 26
	DnsType_DNS_TYPE_GPOS        DnsType = 27
	DnsType_DNS_TYPE_AAAA        DnsType = 28
	DnsType_DNS_TYPE_LOC         DnsType = 29
	DnsType_DNS_TYPE_NXT         DnsType = 30
	DnsType_DNS_TYPE_EID         DnsType = 31
	DnsType_DNS_TYPE_NIMLOC      DnsType = 32
	DnsType_DNS_TYPE_SRV         DnsType = 33
	DnsType_DNS_TYPE_ATMA        DnsType = 34
	DnsType_DNS_TYPE_NAPTR       DnsType = 35
	DnsType_DNS_TYPE_KX          DnsType = 36
	DnsType_DNS_TYPE_CERT        DnsType = 37
	DnsType_DNS_TYPE_DNAME       DnsType = 39
	DnsType_DNS_TYPE_OPT         DnsType = 41 // EDNS
	DnsType_DNS_TYPE_APL         DnsType = 42
	DnsType_DNS_TYPE_DS          DnsType = 43
	DnsType_DNS_TYPE_SSHFP       DnsType = 44
	DnsType_DNS_TYPE_IPSECKEY    DnsType = 45
	DnsType_DNS_TYPE_RRSIG       DnsType = 46
	DnsType_DNS_TYPE_NSEC        DnsType = 47
	DnsType_DNS_TYPE_DNSKEY      DnsType = 48
	DnsType_DNS_TYPE_DHCID       DnsType = 49
	DnsType_DNS_TYPE_NSEC3       DnsType = 50
	DnsType_DNS_TYPE_NSEC3PARAM  DnsType = 51
	DnsType_DNS_TYPE_TLSA        DnsType = 52
	DnsType_DNS_TYPE_SMIMEA      DnsType = 53
	DnsType_DNS_TYPE_HIP         DnsType = 55
	DnsType_DNS_TYPE_NINFO       DnsType = 56
	DnsType_DNS_TYPE_RKEY        DnsType = 57
	DnsType_DNS_TYPE_TALINK      DnsType = 58
	DnsType_DNS_TYPE_CDS         DnsType = 59
	DnsType_DNS_TYPE_CDNSKEY     DnsType = 60
	DnsType_DNS_TYPE_OPENPGPKEY  DnsType = 61
	DnsType_DNS_TYPE_CSYNC       DnsType = 62
	DnsType_DNS_TYPE_ZONEMD      DnsType = 63
	DnsType_DNS_TYPE_SVCB        DnsType = 64
	DnsType_DNS_TYPE_HTTPS       DnsType = 65
	DnsType_DNS_TYPE_SPF         DnsType = 99
	DnsType_DNS_TYPE_UINFO       DnsType = 100
	DnsType_DNS_TYPE_UID         DnsType = 101
	DnsType_DNS_TYPE_GID         DnsType = 102
	DnsType_DNS_TYPE_UNSPEC      DnsType = 103
	DnsType_DNS_TYPE_NID         DnsType = 104
	DnsType_DNS_TYPE_L32         DnsType = 105
	DnsType_DNS_TYPE_L64         DnsType = 106
	DnsType_DNS_TYPE_LP          DnsType = 107
	DnsType_DNS_TYPE_EUI48       DnsType = 108
	DnsType_DNS_TYPE_EUI64       DnsType = 109
	DnsType_DNS_TYPE_NXNAME      DnsType = 128
	DnsType_DNS_TYPE_URI         DnsType = 256
	DnsType_DNS_TYPE_CAA         DnsType = 257
	DnsType_DNS_TYPE_AVC         DnsType = 258
	DnsType_DNS_TYPE_AMTRELAY    DnsType = 260
	DnsType_DNS_TYPE_RESINFO     DnsType = 261
	// Transaction / meta
	DnsType_DNS_TYPE_TKEY DnsType = 249
	DnsType_DNS_TYPE_TSIG DnsType = 250
	// QTYPE-only values
	DnsType_DNS_TYPE_IXFR  DnsType = 251
	DnsType_DNS_TYPE_AXFR  DnsType = 252
	DnsType_DNS_TYPE_MAILB DnsType = 253
	DnsType_DNS_TYPE_MAILA DnsType = 254
	DnsType_DNS_TYPE_ANY   DnsType = 255
)

// Enum value maps for DnsType.
var (
	DnsType_name = map[int32]string{
		0:   "DNS_TYPE_UNSPECIFIED",
		1:   "DNS_TYPE_A",
		2:   "DNS_TYPE_NS",
		3:   "DNS_TYPE_MD",
		4:   "DNS_TYPE_MF",
		5:   "DNS_TYPE_CNAME",
		6:   "DNS_TYPE_SOA",
		7:   "DNS_TYPE_MB",
		8:   "DNS_TYPE_MG",
		9:   "DNS_TYPE_MR",
		10:  "DNS_TYPE_NULL",
		12:  "DNS_TYPE_PTR",
		13:  "DNS_TYPE_HINFO",
		14:  "DNS_TYPE_MINFO",
		15:  "DNS_TYPE_MX",
		16:  "DNS_TYPE_TXT",
		17:  "DNS_TYPE_RP",
		18:  "DNS_TYPE_AFSDB",
		19:  "DNS_TYPE_X25",
		20:  "DNS_TYPE_ISDN",
		21:  "DNS_TYPE_RT",
		23:  "DNS_TYPE_NSAP_PTR",
		24:  "DNS_TYPE_SIG",
		25:  "DNS_TYPE_KEY",
		26:  "DNS_TYPE_PX",
		27:  "DNS_TYPE_GPOS",
		28:  "DNS_TYPE_AAAA",
		29:  "DNS_TYPE_LOC",
		30:  "DNS_TYPE_NXT",
		31:  "DNS_TYPE_EID",
		32:  "DNS_TYPE_NIMLOC",
		33:  "DNS_TYPE_SRV",
		34:  "DNS_TYPE_ATMA",
		35:  "DNS_TYPE_NAPTR",
		36:  "DNS_TYPE_KX",
		37:  "DNS_TYPE_CERT",
		39:  "DNS_TYPE_DNAME",
		41:  "DNS_TYPE_OPT",
		42:  "DNS_TYPE_APL",
		43:  "DNS_TYPE_DS",
		44:  "DNS_TYPE_SSHFP",
		45:  "DNS_TYPE_IPSECKEY",
		46:  "DNS_TYPE_RRSIG",
		47:  "DNS_TYPE_NSEC",
		48:  "DNS_TYPE_DNSKEY",
		49:  "DNS_TYPE_DHCID",
		50:  "DNS_TYPE_NSEC3",
		51:  "DNS_TYPE_NSEC3PARAM",
		52:  "DNS_TYPE_TLSA",
		53:  "DNS_TYPE_SMIMEA",
		55:  "DNS_TYPE_HIP",
		56:  "DNS_TYPE_NINFO",
		57:  "DNS_TYPE_RKEY",
		58:  "DNS_TYPE_TALINK",
		59:  "DNS_TYPE_CDS",
		60:  "DNS_TYPE_CDNSKEY",
		61:  "DNS_TYPE_OPENPGPKEY",
		62:  "DNS_TYPE_CSYNC",
		63:  "DNS_TYPE_ZONEMD",
		64:  "DNS_TYPE_SVCB",
		65:  "DNS_TYPE_HTTPS",
		99:  "DNS_TYPE_SPF",
		100: "DNS_TYPE_UINFO",
		101: "DNS_TYPE_UID",
		102: "DNS_TYPE_GID",
		103: "DNS_TYPE_UNSPEC",
		104: "DNS_TYPE_NID",
		105: "DNS_TYPE_L32",
		106: "DNS_TYPE_L64",
		107: "DNS_TYPE_LP",
		108: "DNS_TYPE_EUI48",
		109: "DNS_TYPE_EUI64",
		128: "DNS_TYPE_NXNAME",
		256: "DNS_TYPE_URI",
		257: "DNS_TYPE_CAA",
		258: "DNS_TYPE_AVC",
		260: "DNS_TYPE_AMTRELAY",
		261: "DNS_TYPE_RESINFO",
		249: "DNS_TYPE_TKEY",
		250: "DNS_TYPE_TSIG",
		251: "DNS_TYPE_IXFR",
		252: "DNS_TYPE_AXFR",
		253: "DNS_TYPE_MAILB",
		254: "DNS_TYPE_MAILA",
		255: "DNS_TYPE_ANY",
	}
	DnsType_value = map[string]int32{
		"DNS_TYPE_UNSPECIFIED": 0,
		"DNS_TYPE_A":           1,
		"DNS_TYPE_NS":          2,
		"DNS_TYPE_MD":          3,
		"DNS_TYPE_MF":          4,
		"DNS_TYPE_CNAME":       5,
		"DNS_TYPE_SOA":         6,
		"DNS_TYPE_MB":          7,
		"DNS_TYPE_MG":          8,
		"DNS_TYPE_MR":          9,
		"DNS_TYPE_NULL":        10,
		"DNS_TYPE_PTR":         12,
		"DNS_TYPE_HINFO":       13,
		"DNS_TYPE_MINFO":       14,
		"DNS_TYPE_MX":          15,
		"DNS_TYPE_TXT":         16,
		"DNS_TYPE_RP":          17,
		"DNS_TYPE_AFSDB":       18,
		"DNS_TYPE_X25":         19,
		"DNS_TYPE_ISDN":        20,
		"DNS_TYPE_RT":          21,
		"DNS_TYPE_NSAP_PTR":    23,
		"DNS_TYPE_SIG":         24,
		"DNS_TYPE_KEY":         25,
		"DNS_TYPE_PX":          26,
		"DNS_TYPE_GPOS":        27,
		"DNS_TYPE_AAAA":        28,
		"DNS_TYPE_LOC":         29,
		"DNS_TYPE_NXT":         30,
		"DNS_TYPE_EID":         31,
		"DNS_TYPE_NIMLOC":      32,
		"DNS_TYPE_SRV":         33,
		"DNS_TYPE_ATMA":        34,
		"DNS_TYPE_NAPTR":       35,
		"DNS_TYPE_KX":          36,
		"DNS_TYPE_CERT":        37,
		"DNS_TYPE_DNAME":       39,
		"DNS_TYPE_OPT":         41,
		"DNS_TYPE_APL":         42,
		"DNS_TYPE_DS":          43,
		"DNS_TYPE_SSHFP":       44,
		"DNS_TYPE_IPSECKEY":    45,
		"DNS_TYPE_RRSIG":       46,
		"DNS_TYPE_NSEC":        47,
		"DNS_TYPE_DNSKEY":      48,
		"DNS_TYPE_DHCID":       49,
		"DNS_TYPE_NSEC3":       50,
		"DNS_TYPE_NSEC3PARAM":  51,
		"DNS_TYPE_TLSA":        52,
		"DNS_TYPE_SMIMEA":      53,
		"DNS_TYPE_HIP":         55,
		"DNS_TYPE_NINFO":       56,
		"DNS_TYPE_RKEY":        57,
		"DNS_TYPE_TALINK":      58,
		"DNS_TYPE_CDS":         59,
		"DNS_TYPE_CDNSKEY":     60,
		"DNS_TYPE_OPENPGPKEY":  61,
		"DNS_TYPE_CSYNC":       62,
		"DNS_TYPE_ZONEMD":      63,
		"DNS_TYPE_SVCB":        64,
		"DNS_TYPE_HTTPS":       65,
		"DNS_TYPE_SPF":         99,
		"DNS_TYPE_UINFO":       100,
		"DNS_TYPE_UID":         101,
		"DNS_TYPE_GID":         102,
		"DNS_TYPE_UNSPEC":      103,
		"DNS_TYPE_NID":         104,
		"DNS_TYPE_L32":         105,
		"DNS_TYPE_L64":         106,
		"DNS_TYPE_LP":          107,
		"DNS_TYPE_EUI48":       108,
		"DNS_TYPE_EUI64":       109,
		"DNS_TYPE_NXNAME":      128,
		"DNS_TYPE_URI":         256,
		"DNS_TYPE_CAA":         257,
		"DNS_TYPE_AVC":         258,
		"DNS_TYPE_AMTRELAY":    260,
		"DNS_TYPE_RESINFO":     261,
		"DNS_TYPE_TKEY":        249,
		"DNS_TYPE_TSIG":        250,
		"DNS_TYPE_IXFR":        251,
		"DNS_TYPE_AXFR":        252,
		"DNS_TYPE_MAILB":       253,
		"DNS_TYPE_MAILA":       254,
		"DNS_TYPE_ANY":         255,
	}
)

func (x DnsType) Enum() *DnsType {
	p := new(DnsType)
	*p = x
	return p
}

func (x DnsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DnsType) Descriptor() protoreflect.EnumDescriptor {
	return file_dns_proto_enumTypes[0].Descriptor()
}

func (DnsType) Type() protoreflect.EnumType {
	return &file_dns_proto_enumTypes[0]
}

func (x DnsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DnsType.Descriptor instead.
func (DnsType) EnumDescriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{0}
}

var File_dns_proto protoreflect.FileDescriptor

const file_dns_proto_rawDesc = "" +
	"\n" +
	"\tdns.proto\x12\bconfigpb*\xf5\f\n" +
	"\aDnsType\x12\x18\n" +
	"\x14DNS_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"DNS_TYPE_A\x10\x01\x12\x0f\n" +
	"\vDNS_TYPE_NS\x10\x02\x12\x0f\n" +
	"\vDNS_TYPE_MD\x10\x03\x12\x0f\n" +
	"\vDNS_TYPE_MF\x10\x04\x12\x12\n" +
	"\x0eDNS_TYPE_CNAME\x10\x05\x12\x10\n" +
	"\fDNS_TYPE_SOA\x10\x06\x12\x0f\n" +
	"\vDNS_TYPE_MB\x10\a\x12\x0f\n" +
	"\vDNS_TYPE_MG\x10\b\x12\x0f\n" +
	"\vDNS_TYPE_MR\x10\t\x12\x11\n" +
	"\rDNS_TYPE_NULL\x10\n" +
	"\x12\x10\n" +
	"\fDNS_TYPE_PTR\x10\f\x12\x12\n" +
	"\x0eDNS_TYPE_HINFO\x10\r\x12\x12\n" +
	"\x0eDNS_TYPE_MINFO\x10\x0e\x12\x0f\n" +
	"\vDNS_TYPE_MX\x10\x0f\x12\x10\n" +
	"\fDNS_TYPE_TXT\x10\x10\x12\x0f\n" +
	"\vDNS_TYPE_RP\x10\x11\x12\x12\n" +
	"\x0eDNS_TYPE_AFSDB\x10\x12\x12\x10\n" +
	"\fDNS_TYPE_X25\x10\x13\x12\x11\n" +
	"\rDNS_TYPE_ISDN\x10\x14\x12\x0f\n" +
	"\vDNS_TYPE_RT\x10\x15\x12\x15\n" +
	"\x11DNS_TYPE_NSAP_PTR\x10\x17\x12\x10\n" +
	"\fDNS_TYPE_SIG\x10\x18\x12\x10\n" +
	"\fDNS_TYPE_KEY\x10\x19\x12\x0f\n" +
	"\vDNS_TYPE_PX\x10\x1a\x12\x11\n" +
	"\rDNS_TYPE_GPOS\x10\x1b\x12\x11\n" +
	"\rDNS_TYPE_AAAA\x10\x1c\x12\x10\n" +
	"\fDNS_TYPE_LOC\x10\x1d\x12\x10\n" +
	"\fDNS_TYPE_NXT\x10\x1e\x12\x10\n" +
	"\fDNS_TYPE_EID\x10\x1f\x12\x13\n" +
	"\x0fDNS_TYPE_NIMLOC\x10 \x12\x10\n" +
	"\fDNS_TYPE_SRV\x10!\x12\x11\n" +
	"\rDNS_TYPE_ATMA\x10\"\x12\x12\n" +
	"\x0eDNS_TYPE_NAPTR\x10#\x12\x0f\n" +
	"\vDNS_TYPE_KX\x10$\x12\x11\n" +
	"\rDNS_TYPE_CERT\x10%\x12\x12\n" +
	"\x0eDNS_TYPE_DNAME\x10'\x12\x10\n" +
	"\fDNS_TYPE_OPT\x10)\x12\x10\n" +
	"\fDNS_TYPE_APL\x10*\x12\x0f\n" +
	"\vDNS_TYPE_DS\x10+\x12\x12\n" +
	"\x0eDNS_TYPE_SSHFP\x10,\x12\x15\n" +
	"\x11DNS_TYPE_IPSECKEY\x10-\x12\x12\n" +
	"\x0eDNS_TYPE_RRSIG\x10.\x12\x11\n" +
	"\rDNS_TYPE_NSEC\x10/\x12\x13\n" +
	"\x0fDNS_TYPE_DNSKEY\x100\x12\x12\n" +
	"\x0eDNS_TYPE_DHCID\x101\x12\x12\n" +
	"\x0eDNS_TYPE_NSEC3\x102\x12\x17\n" +
	"\x13DNS_TYPE_NSEC3PARAM\x103\x12\x11\n" +
	"\rDNS_TYPE_TLSA\x104\x12\x13\n" +
	"\x0fDNS_TYPE_SMIMEA\x105\x12\x10\n" +
	"\fDNS_TYPE_HIP\x107\x12\x12\n" +
	"\x0eDNS_TYPE_NINFO\x108\x12\x11\n" +
	"\rDNS_TYPE_RKEY\x109\x12\x13\n" +
	"\x0fDNS_TYPE_TALINK\x10:\x12\x10\n" +
	"\fDNS_TYPE_CDS\x10;\x12\x14\n" +
	"\x10DNS_TYPE_CDNSKEY\x10<\x12\x17\n" +
	"\x13DNS_TYPE_OPENPGPKEY\x10=\x12\x12\n" +
	"\x0eDNS_TYPE_CSYNC\x10>\x12\x13\n" +
	"\x0fDNS_TYPE_ZONEMD\x10?\x12\x11\n" +
	"\rDNS_TYPE_SVCB\x10@\x12\x12\n" +
	"\x0eDNS_TYPE_HTTPS\x10A\x12\x10\n" +
	"\fDNS_TYPE_SPF\x10c\x12\x12\n" +
	"\x0eDNS_TYPE_UINFO\x10d\x12\x10\n" +
	"\fDNS_TYPE_UID\x10e\x12\x10\n" +
	"\fDNS_TYPE_GID\x10f\x12\x13\n" +
	"\x0fDNS_TYPE_UNSPEC\x10g\x12\x10\n" +
	"\fDNS_TYPE_NID\x10h\x12\x10\n" +
	"\fDNS_TYPE_L32\x10i\x12\x10\n" +
	"\fDNS_TYPE_L64\x10j\x12\x0f\n" +
	"\vDNS_TYPE_LP\x10k\x12\x12\n" +
	"\x0eDNS_TYPE_EUI48\x10l\x12\x12\n" +
	"\x0eDNS_TYPE_EUI64\x10m\x12\x14\n" +
	"\x0fDNS_TYPE_NXNAME\x10\x80\x01\x12\x11\n" +
	"\fDNS_TYPE_URI\x10\x80\x02\x12\x11\n" +
	"\fDNS_TYPE_CAA\x10\x81\x02\x12\x11\n" +
	"\fDNS_TYPE_AVC\x10\x82\x02\x12\x16\n" +
	"\x11DNS_TYPE_AMTRELAY\x10\x84\x02\x12\x15\n" +
	"\x10DNS_TYPE_RESINFO\x10\x85\x02\x12\x12\n" +
	"\rDNS_TYPE_TKEY\x10\xf9\x01\x12\x12\n" +
	"\rDNS_TYPE_TSIG\x10\xfa\x01\x12\x12\n" +
	"\rDNS_TYPE_IXFR\x10\xfb\x01\x12\x12\n" +
	"\rDNS_TYPE_AXFR\x10\xfc\x01\x12\x13\n" +
	"\x0eDNS_TYPE_MAILB\x10\xfd\x01\x12\x13\n" +
	"\x0eDNS_TYPE_MAILA\x10\xfe\x01\x12\x11\n" +
	"\fDNS_TYPE_ANY\x10\xff\x01B6Z4github.com/buglloc/sly64/v2/internal/config/configpbb\x06proto3"

var (
	file_dns_proto_rawDescOnce sync.Once
	file_dns_proto_rawDescData []byte
)

func file_dns_proto_rawDescGZIP() []byte {
	file_dns_proto_rawDescOnce.Do(func() {
		file_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)))
	})
	return file_dns_proto_rawDescData
}

var file_dns_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dns_proto_goTypes = []any{
	(DnsType)(0), // 0: configpb.DnsType
}
var file_dns_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dns_proto_init() }
func file_dns_proto_init() {
	if File_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dns_proto_goTypes,
		DependencyIndexes: file_dns_proto_depIdxs,
		EnumInfos:         file_dns_proto_enumTypes,
	}.Build()
	File_dns_proto = out.File
	file_dns_proto_goTypes = nil
	file_dns_proto_depIdxs = nil
}
